[package]
name = "unarm"
version = "1.0.0"
edition = "2021"
authors = ["Aetias <aetias@outlook.com>"]
license = "MIT"
description = "Disassembles ARM instructions"
keywords = ["arm", "armv5te"]
repository = "https://github.com/AetiasHax/armv5te"
readme = "../README.md"

[features]
default = ["thumb", "arm", "v4t", "v5te", "v6k"]
thumb = []
arm = []
v4t = []
v5te = []
v6k = []

[dependencies]
